import { getInitialSettings } from '../utils/settings/settings.js'

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  if (!config) {
    return SPINNER_VERBS
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : SPINNER_VERBS
  }
  return [...SPINNER_VERBS, ...config.verbs]
}

// Spinner verbs for loading messages (PT-BR + Gírias Cariocas + Memes)
export const SPINNER_VERBS = [
  // --- PT-BR ---
  'Acomodando',
  'Agindo',
  'Atualizando',
  'Arquitetando',
  'Assando',
  'Brilhando',
  'Bebopando',
  'Desconsertando',
  'Ondulando',
  'Borrifando',
  'Blaterando',
  'Boogieando',
  'Zanzando',
  'Cutucando',
  'Inicializando',
  'Brewando',
  'Bunnando',
  'Escavando',
  'Calculando',
  'Aconchegando',
  'Caramelizando',
  'Cascateando',
  'Catapultando',
  'Cerebrando',
  'Canalizando',
  'Escoando',
  'Coreografando',
  'Chacoalhando',
  'Claudiando',
  'Coalescendo',
  'Cogitando',
  'Embananando',
  'Compondo',
  'Computando',
  'Concoctando',
  'Considerando',
  'Contemplando',
  'Cozinhando',
  'Criando',
  'Triturando',
  'Cristalizando',
  'Cultivando',
  'Decifrando',
  'Deliberando',
  'Determinando',
  'Enrolando',
  'Desembananando',
  'Fazendo',
  'Rabiscando',
  'Garoeando',
  'Minguando',
  'Efetuando',
  'Elucidando',
  'Embelezando',
  'Encantando',
  'Vislumbrando',
  'Evaporando',
  'Fermentando',
  'Frescurando',
  'Jeitando',
  'Flambeando',
  'Tagarelando',
  'Fluindo',
  'Embaralhando',
  'Borboleteando',
  'Forjando',
  'Formando',
  'Brincando',
  'Geleando',
  'Passeando',
  'Galopando',
  'Guarnecendo',
  'Gerando',
  'Gesticulando',
  'Germinando',
  'Gitificando',
  'Groovando',
  'Rajando',
  'Harmonizando',
  'Hasheando',
  'Chocando',
  'Rebanhando',
  'Buzinando',
  'Festejando',
  'Hiperviajando',
  'Ideando',
  'Imaginando',
  'Improvisando',
  'Incubando',
  'Inferindo',
  'Infundindo',
  'Ionizando',
  'Jitterbugando',
  'Fatiando',
  'Amassando',
  'Crescendo',
  'Levitando',
  'Vagueando',
  'Manifestando',
  'Marinando',
  'Serpenteando',
  'Metamorfoseando',
  'Nebulizando',
  'Moonwalkando',
  'Percorrendo',
  'Ruminando',
  'Reunindo',
  'Meditando',
  'Aninhando',
  'Jornaleando',
  'Noodleando',
  'Nucleando',
  'Orbitando',
  'Orquestrando',
  'Osmosando',
  'Perambulando',
  'Percolando',
  'Examinando',
  'Filosofando',
  'Fotossintetizando',
  'Polinizando',
  'Ponderando',
  'Pontificando',
  'Saltando',
  'Precipitando',
  'Prestidigitando',
  'Processando',
  'Revisando',
  'Propagando',
  'Intrigando',
  'Quantumizando',
  'Deslumbrando',
  'Esbanjando',
  'Reticulando',
  'Pousando',
  'Salteando',
  'Correndo',
  'Arrastando',
  'Esgueirando',
  'Temperando',
  'Zueando',
  'Shimmyando',
  'Fervendo',
  'Debandando',
  'Esboçando',
  'Deslizando',
  'Apertando',
  'Dançando',
  'Explorando',
  'Girando',
  'Brotando',
  'Refogando',
  'Sublimando',
  'Rodopiando',
  'Mergulhando',
  'Simbiotizando',
  'Sintetizando',
  'Modulando',
  'Pensando',
  'Trovejando',
  'Fuçando',
  'Revirando',
  'Transfigurando',
  'Transmutando',
  'Torcendo',
  'Desdobrando',
  'Desenredando',
  'Vibrando',
  'Rebolando',
  'Vagando',
  'Warpando',
  'Trecofazendo',
  'Redemoinhando',
  'Zumbindo',
  'Misturando',
  'Bambaleando',
  'Trabalhando',
  'Domando',
  'Zestando',
  'Zigue-zagueando',

  // --- Gírias Cariocas ---
  'Bolando',
  'Dando um jeitinho',
  'Cavucando',
  'Balançando',
  'Trocando uma ideia',
  'Se virando nos 30',
  'Mandando ver',
  'Arrumando a casa',
  'Sambando',
  'Suingando',
  'Batendo uma bolinha',
  'Pegando a onda',
  'Na correria',
  'Fazendo a mágica',
  'Virando a noite',
  'Ajeitando as parada',
  'Botando ordem na casa',
  'Pensando numa solução',
  'Matutando',
  'Remexendo',
  'Fuçando nos arquivo',
  'Botando bronca',
  'Fazendo o corre',
  'Dando aquele tapa',
  'Mandando o papo reto',
  'Raciocinando',
  'Coçando a cabeça',
  'Tirando de letra',
  'Desenrolando',
  'Afiando os neurônio',
  'Batendo o martelo',
  'Engrenando',
  'Fazendo chover',
  'Jogando a real',
  'Na humildade',
  'Soltando o verbo',
  'Caindo de paraquedas',
  'Dando um tapa no código',
  'Bate e volta no Google',
  'Suando a camisa',
  'Pegando pesado',
  'Mandando o salve',
  'Fazendo vaquinha de código',
  'Rodando liso',

  // --- Memes da Internet ---
  'Stack Overflowando',
  'Debugando com println',
  'Fazendo deploy na sexta',
  'Commitando sem testar',
  'Googleando o erro',
  'Pegando café',
  'Rodeando o bug',
  'Perguntando pro estagiário',
  'Fazendo o que o README manda',
  'Copiando do Stack Overflow',
  'Apagando e fazendo de novo',
  'Reiniciando pra ver se resolve',
  'Olhando pro teto e pensando',
  'Fingindo que tá funcionando',
  'Reza braba ativada',
  'git commit --amend pra sempre',
  'Esperando o CI passar',
  'Esperando o build terminar',
  'Digitando com raiva',
  'Fazendo código gambiarra',
  'Pensando em virar padeiro',
  'Contemplando o void',
  'Fazendo hotfix em produção',
  'Rezar pro código compilar',
  'Ctrl+Z na vida real',
  'Stack Overflow é meu parceiro',
  'Fazendo o LLM pensar muito',
  'Esperando o npm install',
  'node_modules pesando 1TB',
  'Procurando o bug faz 3 horas',
  'Era só um ponto e vírgula',
  'Fazendo merge com medo',
  'git push --force com fé',
  'Esperando o Docker upar',
  'Recusando código no PR',
  'Fingindo que entendeu o código',
  'Rodando 47 tabs do Chrome',
]
